# Generated by Django 3.2.2 on 2021-05-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
    ]
